(() => {
  'use strict';
  const KEY = 'liquid-timetable-v1', SEED_VERSION = 2, COURSE_SEED_VERSION = 5, TIME_PRESET_VERSION = 2;
  const days = ['周一','周二','周三','周四','周五','周六','周日'];
  const SCHOOL_PERIODS = [{start:'08:20',end:'09:00'},{start:'09:10',end:'09:50'},{start:'10:15',end:'10:55',adjustedStart:'10:25',adjustedEnd:'11:05'},{start:'11:05',end:'11:45',adjustedStart:'11:15',adjustedEnd:'11:55'},{start:'14:00',end:'14:40'},{start:'14:50',end:'15:30'},{start:'15:55',end:'16:35'},{start:'16:45',end:'17:25'},{start:'19:00',end:'19:40'},{start:'19:50',end:'20:30'}];
  const $ = s => document.querySelector(s);
  const localISO = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const nextMonday = () => { const d=new Date(); const offset=(8-d.getDay())%7 || 7; d.setDate(d.getDate()+offset); return localISO(d); };
  const course = (id,name,location,day,start,weekStart,weekEnd) => ({id,name,location,day,start,duration:2,weekType:'all',weekStart,weekEnd});
  const defaults = () => ({ settings:{scheduleName:'课表',showCurrentOnly:false,compactView:false,termStart:'2026-08-31',termStartSeedVersion:2, periodCount:10, periodMinutes:40, breakMinutes:10, breakAfter2:25, breakAfter6:25, lunchStart:'11:45', lunchEnd:'14:00', dinnerStart:'17:25', dinnerEnd:'19:00', firstTime:'08:20', usePresetTimes:true,timePresetVersion:TIME_PRESET_VERSION,mapSearchPrefix:'南昌工学院',dormLocation:'南昌工学院学生公寓 9号楼',theme:'auto',seedVersion:SEED_VERSION,courseSeedVersion:COURSE_SEED_VERSION}, courses:[
    course('c01','手工制作','创新楼B-513',1,3,2,16), course('c02','中外教育史','明志楼306',1,7,1,16),
    course('c03','科学技术基础','至善楼504',2,1,9,16), course('c04','AI创意策划与文本创作','至善楼311',2,3,1,16),
    course('c05','多媒体课件制作','卓越楼T-317',3,1,1,16), course('c06','教育心理学','至善楼311',3,5,1,16), course('c07','创业基础','至善楼409',3,7,6,13),
    course('c08','社会实践','明志楼305',4,1,11,12), course('c09','手工制作','致远楼B513',4,1,16,16), course('c10','综合英语Ⅰ','至善楼309',4,3,1,16), course('c11','课程与教学论','思齐楼106',4,5,1,16), course('c12','教育学基础','明志楼308',4,7,1,16),
    course('c13','课程与教学论','明志楼308',5,1,1,16), course('c14','党史国史','明德楼320',5,3,1,16),
    course('c15','科学技术基础','线上教学平台8',6,7,2,9)
  ]});
  function normalizeState(saved){if(!saved?.settings||!Array.isArray(saved.courses))throw Error('课表数据结构不正确');const base=defaults(),settings={...base.settings,...saved.settings,seedVersion:SEED_VERSION};let courses=saved.courses.filter(validCourse).map(c=>({...c,id:String(c.id||`c${Date.now()}${Math.random()}`),name:String(c.name).slice(0,40),location:String(c.location||'').slice(0,50),day:+c.day,start:+c.start,duration:Math.max(1,+c.duration||1),weekType:['all','odd','even'].includes(c.weekType)?c.weekType:'all',weekStart:Math.max(1,+c.weekStart||1),weekEnd:Math.max(1,+c.weekEnd||16)}));if((+saved.settings.courseSeedVersion||0)<COURSE_SEED_VERSION){courses=courses.filter(c=>!/^c(?:0?[1-9]|1[0-6])$/.test(c.id)).concat(base.courses);}if((+saved.settings.termStartSeedVersion||0)<2&&saved.settings.termStart==='2026-09-07')settings.termStart=base.settings.termStart;if((+saved.settings.timePresetVersion||0)<TIME_PRESET_VERSION)settings.usePresetTimes=saved.settings.firstTime==='08:00'&&Number(saved.settings.periodMinutes)===45;settings.mapSearchPrefix=String(settings.mapSearchPrefix||'').trim().slice(0,60);settings.dormLocation=String(settings.dormLocation||'').trim().slice(0,80);delete settings.mapPreference;settings.courseSeedVersion=COURSE_SEED_VERSION;settings.termStartSeedVersion=2;settings.timePresetVersion=TIME_PRESET_VERSION;return {settings,courses};}
  function load(){try{const raw=localStorage.getItem(KEY);if(!raw)return defaults();return normalizeState(JSON.parse(raw));}catch(e){console.warn('本地数据无效，已使用安全默认设置',e);return defaults();}}
  function validCourse(c){return c && typeof c.name==='string' && Number.isInteger(+c.day) && +c.day>=1 && +c.day<=7 && +c.start>=1;}
  let state=load(), editingId=null, viewWeekOffset=0;
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){alert('无法保存到本地浏览器。请检查是否启用了隐私模式或浏览器存储权限。');}}
  function replaceState(candidate){state=normalizeState(candidate);save();render();}
  save();
  function dateAtLocal(iso){const [y,m,d]=iso.split('-').map(Number);return new Date(y,m-1,d);}
  function weekInfoForDate(date){const target=new Date(date);target.setHours(0,0,0,0);const start=dateAtLocal(state.settings.termStart);start.setHours(0,0,0,0);const diff=Math.floor((target-start)/86400000);if(diff<0)return {started:false,week:0,type:null};return {started:true,week:Math.floor(diff/7)+1,type:(Math.floor(diff/7)+1)%2?'odd':'even'};}
  function weekInfo(offsetWeeks=0){const now=new Date();now.setDate(now.getDate()+offsetWeeks*7);return weekInfoForDate(now);}
  function minutesOf(value){const [h,m]=value.split(':').map(Number);return h*60+m;}
  function breakAfter(period){if(period===2)return Number(state.settings.breakAfter2);if(period===6)return Number(state.settings.breakAfter6);return Number(state.settings.breakMinutes||0);}
  function isCentralBuilding(location){return /(明志楼|明德楼|至善楼)/.test(String(location||''));}
  function presetTime(period,location=''){const slot=SCHOOL_PERIODS[period-1];if(!slot)return null;const adjusted=(period===3||period===4)&&location&&!isCentralBuilding(location);return {start:adjusted?slot.adjustedStart||slot.start:slot.start,end:adjusted?slot.adjustedEnd||slot.end:slot.end,adjusted};}
  function customTimeFor(period){let total=minutesOf(state.settings.firstTime),length=Number(state.settings.periodMinutes);for(let completed=1;completed<period;completed++){total+=length;if(completed===4)total=Math.max(total,minutesOf(state.settings.lunchStart),minutesOf(state.settings.lunchEnd));else if(completed===8)total=Math.max(total,minutesOf(state.settings.dinnerStart),minutesOf(state.settings.dinnerEnd));else total+=breakAfter(completed);}return `${String(Math.floor(total/60)%24).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`;}
  function timeFor(period){return state.settings.usePresetTimes&&SCHOOL_PERIODS[period-1]?SCHOOL_PERIODS[period-1].start:customTimeFor(period);}
  function timeEndFor(period){if(state.settings.usePresetTimes&&SCHOOL_PERIODS[period-1])return SCHOOL_PERIODS[period-1].end;const total=minutesOf(customTimeFor(period))+Number(state.settings.periodMinutes);return `${String(Math.floor(total/60)%24).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`;}
  function courseTimeInfo(course){if(!state.settings.usePresetTimes)return null;const start=presetTime(course.start,course.location),end=presetTime(Math.min(course.start+course.duration-1,SCHOOL_PERIODS.length),course.location);if(!start||!end)return null;return {text:`${start.start}–${end.end}`,adjusted:start.adjusted||end.adjusted};}
  function courseTiming(course){if(state.settings.usePresetTimes){const start=presetTime(course.start,course.location),end=presetTime(Math.min(course.start+course.duration-1,SCHOOL_PERIODS.length),course.location);if(start&&end)return {start:minutesOf(start.start),end:minutesOf(end.end),text:`${start.start}–${end.end}`,adjusted:start.adjusted||end.adjusted};}const last=Math.min(course.start+course.duration-1,state.settings.periodCount),start=timeFor(course.start),end=timeEndFor(last);return {start:minutesOf(start),end:minutesOf(end),text:`${start}–${end}`,adjusted:false};}
  function format12Hour(minutes){const hour=Math.floor((minutes+1440)%1440/60),minute=(minutes+1440)%1440%60,period=hour<12?'上午':hour<18?'下午':'晚上',display=hour%12||12;return `${period} ${display}:${String(minute).padStart(2,'0')}`;}
  function lessonDateLabel(date,now){const day=new Date(date);day.setHours(0,0,0,0);const today=new Date(now);today.setHours(0,0,0,0);const diff=Math.round((day-today)/86400000);return diff===0?'今天':diff===1?'明天':days[(day.getDay()||7)-1];}
  function lessonsOn(date){const info=weekInfoForDate(date),day=date.getDay()||7;if(!info.started)return [];return state.courses.filter(course=>course.day===day&&isActive(course,info)).map(course=>({course,date:new Date(date),timing:courseTiming(course)})).sort((a,b)=>a.timing.start-b.timing.start);}
  function findNextLesson(now,minStart){for(let offset=0;offset<=21;offset++){const date=new Date(now);date.setDate(now.getDate()+offset);const threshold=offset===0?minStart:-1;const lesson=lessonsOn(date).find(item=>item.timing.start>threshold);if(lesson)return lesson;}return null;}
  function buildingFromLocation(location){const match=String(location||'').match(/([\u3400-\u9fff]+楼)/);return match?match[1]:null;}
  function lessonCardMarkup(lesson,now){const course=lesson.course,building=buildingFromLocation(course.location);return `<article class="reminder-course"><h3>${escapeHTML(course.name)}</h3><p>${lessonDateLabel(lesson.date,now)} · ${days[course.day-1]} · 第 ${course.start}–${course.start+course.duration-1} 节</p><p>${escapeHTML(course.location||'未填写地点')} · ${lesson.timing.text}</p><p>${weekLabel(course)}${lesson.timing.adjusted?' · 场地时间调整':''}</p>${building?`<button type="button" class="reminder-nav-btn" data-map-building="${escapeHTML(building)}">导航过去</button>`:''}</article>`;}
  function currentLessonCardMarkup(lesson){const course=lesson.course,building=buildingFromLocation(course.location);return `<article class="reminder-course"><h3>${escapeHTML(course.name)}</h3><p>${escapeHTML(course.location||'未填写地点')}</p>${building?`<button type="button" class="reminder-nav-btn" data-map-building="${escapeHTML(building)}">导航过去</button>`:''}</article>`;}
  function format24Hour(minutes){const value=(minutes+1440)%1440;return `${String(Math.floor(value/60)).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;}
  function renderNextCourseCard(){const now=new Date(),nowMinutes=now.getHours()*60+now.getMinutes(),todayLessons=lessonsOn(now),current=todayLessons.filter(item=>nowMinutes>=item.timing.start&&nowMinutes<item.timing.end),next=findNextLesson(now,nowMinutes),status=$('#nextCourseStatus'),content=$('#nextCourseContent'),currentSection=$('#currentCourseSection'),currentContent=$('#currentCourseContent');$('#dormMapBtn').hidden=!state.settings.dormLocation;currentSection.hidden=current.length===0;currentContent.innerHTML=current.map(currentLessonCardMarkup).join('');if(!next){status.textContent='';content.innerHTML='<p class="next-course-empty">接下来三周未查询到符合当前教学周的课程。</p>';return;}const departure=next.timing.start-20,alreadyDue=next.date.toDateString()===now.toDateString()&&departure<=nowMinutes;status.textContent=`${lessonDateLabel(next.date,now)} · ${days[next.course.day-1]}`;content.innerHTML=`${lessonCardMarkup(next,now)}<div class="reminder-time"><strong>${alreadyDue?'建议现在出发':'预计出发：'+format24Hour(departure)}</strong><small>${alreadyDue?'已进入建议出发时间。':`提前 20 分钟 · 12 小时制：${format12Hour(departure)}`}</small></div>`;}
  function openMapSearch(target){const query=encodeURIComponent(target),isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);window.location.href=isIOS?`maps://?q=${query}`:`https://maps.apple.com/?q=${query}`;}
  function openBuildingMap(building){openMapSearch([state.settings.mapSearchPrefix,building].filter(Boolean).join(' '));}
  function showEntryReminder(){const now=new Date(),nowMinutes=now.getHours()*60+now.getMinutes(),todayLessons=lessonsOn(now),current=todayLessons.filter(item=>nowMinutes>=item.timing.start&&nowMinutes<item.timing.end);let title='',body='';if(current.length){const next=findNextLesson(now,Math.max(...current.map(item=>item.timing.end)));title='正在上课';body=next?`<p class="reminder-message">当前正在上课。下一节课程如下：</p>${lessonCardMarkup(next,now)}`:'<p class="reminder-message">当前正在上课，接下来三周未查询到下一节课程。</p>';}else{const next=findNextLesson(now,nowMinutes);title='下一节课提醒';if(next){const departure=next.timing.start-20,alreadyDue=next.date.toDateString()===now.toDateString()&&departure<=nowMinutes;body=`<p class="reminder-message">${lessonDateLabel(next.date,now)}的下一节课如下。${alreadyDue?'建议现在出发。':'建议提前 20 分钟出发。'}</p>${lessonCardMarkup(next,now)}<div class="reminder-time"><strong>出发时间：${String(Math.floor((departure+1440)%1440/60)).padStart(2,'0')}:${String((departure+1440)%1440%60).padStart(2,'0')}</strong><small>12 小时制：${format12Hour(departure)}</small></div>`;}else body='<p class="reminder-message">接下来三周未查询到符合当前教学周的课程。</p>';}$('#reminderTitle').textContent=title;$('#reminderBody').innerHTML=body;$('#reminderDialog').showModal();}
  function isActive(c,info){return !info.started || (info.week>=c.weekStart && info.week<=c.weekEnd && (c.weekType==='all'||c.weekType===info.type));}
  function conflictPairs(courses=state.courses){const pairs=[];for(let i=0;i<courses.length;i++)for(let j=i+1;j<courses.length;j++){const a=courses[i],b=courses[j];if(a.day===b.day&&a.start<b.start+b.duration&&b.start<a.start+a.duration)pairs.push([a,b]);}return pairs;}
  function conflicts(courses=state.courses){return new Set(conflictPairs(courses).flatMap(pair=>pair.map(course=>course.id)));}
  function weekLabel(course){return course.weekStart===course.weekEnd?`第${course.weekStart}周`:`${course.weekStart}-${course.weekEnd}周`;}
  function render(){const info=weekInfo(viewWeekOffset), now=new Date(), today=now.getDay()||7;document.body.classList.toggle('dark',state.settings.theme==='dark'||(state.settings.theme==='auto'&&matchMedia('(prefers-color-scheme: dark)').matches));
    $('#scheduleTitle').textContent=state.settings.scheduleName||'课表'; $('#todayText').textContent=now.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
    $('#weekStatus').textContent=info.started?`第 ${info.week} 周 · ${info.type==='odd'?'单周':'双周'} · ${days[today-1]}`:'尚未开学';
    $('#weekNumber').textContent=info.started?info.week:'—'; $('#termHint').textContent=info.started?(viewWeekOffset?`正在预览${viewWeekOffset>0?'后':'前'} ${Math.abs(viewWeekOffset)} 周课程。`:'课表会根据当前单双周自动显示。'):`教学周将于 ${state.settings.termStart} 开始`;
    renderNextCourseCard();
    const grid=$('#schedule');grid.classList.toggle('compact',Boolean(state.settings.compactView));$('#compactViewBtn').classList.toggle('is-active',Boolean(state.settings.compactView));$('#compactViewBtn').setAttribute('aria-pressed',String(Boolean(state.settings.compactView)));grid.style.setProperty('--periods',state.settings.periodCount);grid.innerHTML='<div class="corner"></div>';
    days.forEach((d,i)=>grid.insertAdjacentHTML('beforeend',`<div class="day-head ${i+1===today?'today':''}"><span>${d}</span><small>${i+1===today?'今天':''}</small></div>`));
    for(let p=1;p<=state.settings.periodCount;p++){
      grid.insertAdjacentHTML('beforeend',`<div class="time-label" style="grid-column:1;grid-row:${p+1}"><b>第 ${p} 节</b><br>${timeFor(p)}<br>${timeEndFor(p)}</div>`);
      for(let d=1;d<=7;d++) grid.insertAdjacentHTML('beforeend',`<div class="slot ${d===today?'today-col':''}" style="grid-column:${d+1};grid-row:${p+1}"></div>`);
    }
    const onlyCurrent=Boolean(state.settings.showCurrentOnly),compact=Boolean(state.settings.compactView),visibleCourses=onlyCurrent?state.courses.filter(course=>isActive(course,info)):state.courses,trouble=conflicts(visibleCourses);$('#conflictBtn').hidden=trouble.size===0;$('#weekOnlyBtn').classList.toggle('is-active',onlyCurrent);$('#weekOnlyBtn').setAttribute('aria-pressed',String(onlyCurrent));$('#currentWeekBtn').hidden=viewWeekOffset===0;state.courses.forEach(c=>{if(c.start>state.settings.periodCount)return;const end=Math.min(c.start+c.duration-1,state.settings.periodCount),active=isActive(c,info),weeks=weekLabel(c),conflicted=trouble.has(c.id),time=courseTimeInfo(c);if(onlyCurrent&&!active)return;const item=document.createElement('article');item.className=`course ${active?'':'inactive'} ${conflicted?'conflicted':''}`;item.style.gridColumn=String(c.day+1);item.style.gridRow=`${c.start+1} / ${end+2}`;item.innerHTML=`<button title="编辑 ${escapeHTML(c.name)}" aria-label="编辑课程">⋯</button><div class="course-name">${escapeHTML(c.name)}</div><div class="course-place">${escapeHTML(c.location||'未填写地点')}</div>${compact?'':`${time?`<div class="course-time ${time.adjusted?'adjusted':''}">上课：${time.text}${time.adjusted?'<small>场地时间调整</small>':''}</div>`:''}<div class="course-week">${weeks}</div>${active?'':'<div class="course-status">本周不上课</div>'}${conflicted?'<div class="course-conflict-status">★ 课程冲突</div>':''}`}`;item.querySelector('button').onclick=()=>openCourse(c);enableCourseLongPress(item,c);grid.append(item);});
    const visibleCount=state.courses.filter(course=>!onlyCurrent||isActive(course,info)).length;$('#scheduleHint').textContent=state.courses.length?`${onlyCurrent?`显示 ${visibleCount} 门本周课程`:`${state.courses.length} 门课程`} · ${info.started?(info.type==='odd'?'当前单周':'当前双周'):'开学后自动切换'}`:'还没有课程，点击“添加课程”开始。';
  }
  function escapeHTML(s){return String(s).replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]));}
  function enableCourseLongPress(item,course){let timer=null;const cancel=()=>{if(timer!==null){clearTimeout(timer);timer=null;}};item.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'||event.target.closest('button'))return;timer=setTimeout(()=>{timer=null;if(navigator.vibrate)navigator.vibrate(12);openCourse(course);},500);});['pointerup','pointercancel','pointerleave','pointermove'].forEach(type=>item.addEventListener(type,cancel));}
  function selectOptions(sel, max, selected=1){sel.innerHTML=Array.from({length:max},(_,i)=>`<option value="${i+1}" ${i+1===+selected?'selected':''}>${i+1}</option>`).join('');}
  function syncCourseInputs(c={}){selectOptions($('#courseDay'),7,c.day||1);selectOptions($('#courseStart'),state.settings.periodCount,c.start||1);const max=Math.max(1,state.settings.periodCount-(+$('#courseStart').value||1)+1);selectOptions($('#courseDuration'),max,Math.min(c.duration||1,max));selectOptions($('#courseWeekStart'),32,c.weekStart||1);selectOptions($('#courseWeekEnd'),32,c.weekEnd||16);$('#courseStart').onchange=()=>selectOptions($('#courseDuration'),state.settings.periodCount-+$('#courseStart').value+1,1);}
  function openCourse(c){editingId=c?.id||null;$('#courseDialogTitle').textContent=c?'编辑课程':'添加课程';$('#courseId').value=c?.id||'';$('#courseName').value=c?.name||'';$('#courseLocation').value=c?.location||'';$('#courseWeekType').value=c?.weekType||'all';$('#deleteCourseBtn').hidden=!c;$('#conflictNotice').hidden=true;syncCourseInputs(c);$('#courseDialog').showModal();setTimeout(()=>$('#courseName').focus(),100);}
  function settingsFill(){const s=state.settings;$('#scheduleName').value=s.scheduleName||'课表';$('#termStart').value=s.termStart;selectOptions($('#periodCount'),16,s.periodCount);$('#periodMinutes').value=s.periodMinutes;$('#usePresetTimes').checked=Boolean(s.usePresetTimes);$('#breakMinutes').value=s.breakMinutes??10;$('#breakAfter2').value=s.breakAfter2??s.breakMinutes??10;$('#breakAfter6').value=s.breakAfter6??s.breakMinutes??10;$('#lunchStart').value=s.lunchStart||'11:45';$('#lunchEnd').value=s.lunchEnd||'14:00';$('#dinnerStart').value=s.dinnerStart||'17:25';$('#dinnerEnd').value=s.dinnerEnd||'19:00';$('#firstTime').value=s.firstTime;$('#mapSearchPrefix').value=s.mapSearchPrefix||'';$('#dormLocation').value=s.dormLocation||'';}
  function openConflicts(){const info=weekInfo(viewWeekOffset),source=state.settings.showCurrentOnly?state.courses.filter(course=>isActive(course,info)):state.courses,ids=conflicts(source),courses=source.filter(course=>ids.has(course.id)).sort((a,b)=>a.day-b.day||a.start-b.start);$('#conflictCards').innerHTML=courses.map(course=>`<article class="conflict-card"><h3>${escapeHTML(course.name)}</h3><p>${days[course.day-1]} · 第 ${course.start}–${course.start+course.duration-1} 节 · ${weekLabel(course)}</p><p>${escapeHTML(course.location||'未填写地点')}</p></article>`).join('');$('#conflictDialog').showModal();}
  $('#addBtn').onclick=()=>openCourse();$('#settingsBtn').onclick=()=>{settingsFill();$('#settingsDialog').showModal();};$('#themeBtn').onclick=()=>{state.settings.theme=document.body.classList.contains('dark')?'light':'dark';save();render();};$('#todayBtn').onclick=()=>{viewWeekOffset=0;render();document.querySelector('.day-head.today')?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});};$('#conflictBtn').onclick=openConflicts;$('#compactViewBtn').onclick=()=>{state.settings.compactView=!state.settings.compactView;save();render();};$('#weekOnlyBtn').onclick=()=>{state.settings.showCurrentOnly=!state.settings.showCurrentOnly;save();render();};$('#prevWeekBtn').onclick=()=>{viewWeekOffset--;render();};$('#nextWeekBtn').onclick=()=>{viewWeekOffset++;render();};$('#currentWeekBtn').onclick=()=>{viewWeekOffset=0;render();};
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
  $('#reminderBody').onclick=event=>{const button=event.target.closest('[data-map-building]');if(button)openBuildingMap(button.dataset.mapBuilding);};
  $('#nextCourseContent').onclick=event=>{const button=event.target.closest('[data-map-building]');if(button)openBuildingMap(button.dataset.mapBuilding);};
  $('#currentCourseContent').onclick=event=>{const button=event.target.closest('[data-map-building]');if(button)openBuildingMap(button.dataset.mapBuilding);};
  $('#dormMapBtn').onclick=()=>{if(state.settings.dormLocation)openMapSearch(state.settings.dormLocation);};
  $('#courseForm').onsubmit=e=>{e.preventDefault();const c={id:editingId||`c${Date.now()}`,name:$('#courseName').value.trim(),location:$('#courseLocation').value.trim(),day:+$('#courseDay').value,start:+$('#courseStart').value,duration:+$('#courseDuration').value,weekType:$('#courseWeekType').value,weekStart:+$('#courseWeekStart').value,weekEnd:+$('#courseWeekEnd').value};if(!c.name)return;if(c.weekEnd<c.weekStart){alert('结束教学周不能早于起始教学周。');return;}const old=state.courses;state.courses=editingId?old.map(x=>x.id===editingId?c:x):[...old,c];const hasConflict=conflicts().has(c.id);save();render();$('#courseDialog').close();if(hasConflict) alert('课程已保存，但与同一天、可能同周次的其他课程时间重叠。两门课程均已保留，并会以黄色边框标记。');};
  $('#deleteCourseBtn').onclick=()=>{if(editingId&&confirm('确定删除这门课程吗？此操作不可撤销。')){state.courses=state.courses.filter(c=>c.id!==editingId);save();render();$('#courseDialog').close();}};
  $('#settingsForm').onsubmit=e=>{e.preventDefault();const lunchStart=$('#lunchStart').value,lunchEnd=$('#lunchEnd').value,dinnerStart=$('#dinnerStart').value,dinnerEnd=$('#dinnerEnd').value;if(minutesOf(lunchEnd)<=minutesOf(lunchStart)||minutesOf(dinnerEnd)<=minutesOf(dinnerStart)){alert('午休和晚饭的结束时间必须晚于开始时间。');return;}state.settings={...state.settings,scheduleName:$('#scheduleName').value.trim()||'课表',termStart:$('#termStart').value,periodCount:+$('#periodCount').value,periodMinutes:+$('#periodMinutes').value,usePresetTimes:$('#usePresetTimes').checked,breakMinutes:+$('#breakMinutes').value,breakAfter2:+$('#breakAfter2').value,breakAfter6:+$('#breakAfter6').value,lunchStart,lunchEnd,dinnerStart,dinnerEnd,firstTime:$('#firstTime').value,mapSearchPrefix:$('#mapSearchPrefix').value.trim().slice(0,60),dormLocation:$('#dormLocation').value.trim().slice(0,80)};state.courses=state.courses.map(c=>({...c,start:Math.min(c.start,state.settings.periodCount),duration:Math.min(c.duration,state.settings.periodCount-c.start+1)}));save();render();$('#settingsDialog').close();};
  $('#exportBtn').onclick=()=>{const payload={schemaVersion:1,exportedAt:new Date().toISOString(),data:state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${(state.settings.scheduleName||'静态课表').replace(/[\\/:*?"<>|]/g,'_')}-备份.json`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  $('#importBtn').onclick=()=>$('#importFile').click();
  $('#importFile').onchange=event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result)),candidate=parsed?.data||parsed;normalizeState(candidate);if(!confirm('导入将覆盖当前本机保存的全部课程和设置。建议已完成备份。确定继续吗？'))return;replaceState(candidate);$('#settingsDialog').close();alert('课表数据已成功导入。');}catch(error){console.warn('导入失败',error);alert('无法导入该文件：请选择由“导出课表数据”生成的有效 JSON 备份。');}};reader.onerror=()=>alert('读取备份文件失败，请重试。');reader.readAsText(file,'utf-8');};
  $('#clearBtn').onclick=()=>{if(confirm('确定清空全部课程吗？此操作仅会删除课表课程，且不可撤销。')){state.courses=[];save();render();$('#settingsDialog').close();}};
  $('#resetBtn').onclick=()=>{if(confirm('确定恢复示例课表和默认设置吗？你当前保存的课程与设置将被覆盖。')){state=defaults();save();render();$('#settingsDialog').close();}};
  render();
  showEntryReminder();
  // 行程安排不能只在页面打开时判断：用户停留在页面内跨过上课时间后，
  // 也要切换到“正在上课”的卡片；从后台回到页面时立即重新计算。
  const refreshItinerary=()=>renderNextCourseCard();
  window.setInterval(refreshItinerary,30000);
  window.addEventListener('focus',refreshItinerary);
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshItinerary();});
})();
